#!/usr/bin/env bash
# shell/disk-encryption.sh — workbench-security
# LUKS2 + TPM2 enrollment and passphrase rotation. Registered at tier: lazy
# (.dotfiles-sync.yml) — the last tier the loader sources (see
# workbench-gpg's gpg-management.sh for the same "lazy means last-in-order,
# not deferred-until-called" note — workbench-core's loader tiers have no
# true stub mechanism). Self-guards on Linux, since systemd-cryptenroll has
# no macOS equivalent.
#
# Ported from workbench-precursor's lazy/disk-encryption.sh, functionally
# unchanged except for the Python worker path (below) and Core API renames
# (_str_lower, WORKBENCH_OS).
#
# Slot numbers are NOT pinned. systemd-cryptenroll has no option to choose
# where a new enrollment lands — it always uses cryptsetup's lowest-free-slot
# allocation. The only slot-targeting flag it has, --wipe-slot=, only removes
# slots (by number or by type). So this module identifies and guards
# enrollments by TYPE (password/recovery/tpm2), which is what
# systemd-cryptenroll itself tracks, rather than by slot number. On a
# freshly provisioned device this typically still lands close to: slot 0 =
# install-time passphrase, slot 1 = recovery key, slot 2 = TPM2 — but that's
# an observed outcome of call order, not something enforced.
[[ "${WORKBENCH_OS}" == "Linux" ]] || return 0

# ── LUKS + TPM2 enrollment ─────────────────────────────────────────────────────

# enroll-luks-tpm2
# Discovers LUKS2 partitions and interactively enrolls TPM2 auto-unlock for
# each, one at a time. Before touching any TPM2 slot, guarantees a recovery
# key exists on that device — generating one if missing — so a TPM2 wipe can
# never leave a device with no fallback. TPM2 re-enrollment is scoped to
# `--wipe-slot=tpm2` only; recovery and password slots are never wiped.
#
# Usage:
#   enroll-luks-tpm2
enroll-luks-tpm2() {
    _tpm_require_tools      || return 1
    _tpm_check_tpm2_device  || return 1
    sudo-test                || return 1

    local luks_devices=()
    while IFS= read -r _device; do
        [[ -n "${_device}" ]] && luks_devices+=("${_device}")
    done < <(_tpm_find_luks_devices)

    if [[ ${#luks_devices[@]} -eq 0 ]]; then
        log_error "enroll-luks-tpm2: no LUKS2 partitions found"
        return 1
    fi

    local device_path enrolled_count=0 answer
    for device_path in "${luks_devices[@]}"; do
        echo
        log_info "Found LUKS2 partition: ${device_path}"

        _read_prompt "  Register TPM2 for ${device_path}? [y/N]: " answer
        if [[ "$(_str_lower "${answer}")" != "y" ]]; then
            log_info "Skipping TPM2 enrollment for ${device_path}"
            continue
        fi

        _tpm_enroll_device "${device_path}" && ((enrolled_count++))
    done

    log_info "TPM2 enrollment complete. Enrolled ${enrolled_count} device(s)."
}

# ── LUKS passphrase rotation ───────────────────────────────────────────────────

# rotate-luks-key
# Interactively rotates the passphrase on a LUKS2 device. Prompts for the
# current passphrase and a new one; cryptsetup locates the matching password
# slot itself, so TPM2 and recovery-key slots are never touched. After a
# successful rotation, creates a recovery key only if one is missing — an
# existing recovery key is never wiped or regenerated by this function. If a
# usable TPM2 exists and the device has no TPM2 auto-unlock yet, offers to
# enroll it immediately rather than leaving that as a separate manual step.
#
# Usage:
#   rotate-luks-key
rotate-luks-key() {
    _tpm_require_tools || return 1
    sudo-test            || return 1

    local luks_devices=()
    while IFS= read -r _device; do
        [[ -n "${_device}" ]] && luks_devices+=("${_device}")
    done < <(_tpm_find_luks_devices)

    if [[ ${#luks_devices[@]} -eq 0 ]]; then
        log_error "rotate-luks-key: no LUKS2 partitions found"
        return 1
    fi

    local device_path answer rotated_count=0
    for device_path in "${luks_devices[@]}"; do
        echo
        log_info "Found LUKS2 partition: ${device_path}"

        _read_prompt "  Rotate the passphrase for ${device_path}? [y/N]: " answer
        if [[ "$(_str_lower "${answer}")" != "y" ]]; then
            log_info "Skipping ${device_path}"
            continue
        fi

        echo
        echo "  You'll be prompted for the CURRENT passphrase, then the new one twice."
        echo "  TPM2 and recovery-key slots on this device are not affected."
        echo

        if sudo cryptsetup luksChangeKey "${device_path}"; then
            log_info "Passphrase rotated for ${device_path}"
            ((rotated_count++))
            _tpm_ensure_recovery_key "${device_path}"

            # Cross-link: if a usable TPM2 exists and this device doesn't
            # already have TPM2 auto-unlock, offer to enroll it right here —
            # otherwise the device is left needing a manual passphrase until
            # someone remembers to run enroll-luks-tpm2 separately.
            if _tpm_check_tpm2_device &>/dev/null && ! _tpm_has_token_type "${device_path}" "tpm2"; then
                echo
                _read_prompt "  A usable TPM2 was found and ${device_path} has no TPM2 auto-unlock yet. Enroll it now? [y/N]: " answer
                if [[ "$(_str_lower "${answer}")" == "y" ]]; then
                    _tpm_enroll_device "${device_path}"
                fi
            fi
        else
            log_error "Passphrase rotation failed for ${device_path} — no changes made"
        fi
    done

    log_info "Passphrase rotation complete. Rotated ${rotated_count} device(s)."
}

# ── Internal helpers ───────────────────────────────────────────────────────────

_tpm_require_tools() {
    local cmd
    for cmd in cryptsetup blkid systemd-cryptenroll systemctl python3; do
        if ! command -v "${cmd}" &>/dev/null; then
            log_error "disk-encryption: required tool '${cmd}' is not installed"
            return 1
        fi
    done
}

# Uses systemd-cryptenroll's own device enumeration rather than a separate
# tpm2-tools dependency — it's the same backend that will do the enrolling.
_tpm_check_tpm2_device() {
    local tpm2_list
    tpm2_list="$(systemd-cryptenroll --tpm2-device=list 2>/dev/null)"
    if [[ -z "${tpm2_list}" ]] || ! echo "${tpm2_list}" | grep -q '/dev/tpm'; then
        log_error "enroll-luks-tpm2: no usable TPM2 device found"
        return 1
    fi
}

# Prints every LUKS2 partition path, one per line, via blkid rather than
# lsblk tree-parsing — finds locked and unlocked devices alike. LUKS1
# partitions are detected but skipped with a warning (systemd-cryptenroll
# and this module's rotation flow both target LUKS2 only).
_tpm_find_luks_devices() {
    local dev
    while IFS= read -r dev; do
        [[ -z "${dev}" ]] && continue
        if sudo cryptsetup isLuks --type luks2 "${dev}" 2>/dev/null; then
            echo "${dev}"
        elif sudo cryptsetup isLuks "${dev}" 2>/dev/null; then
            log_warn "disk-encryption: ${dev} is LUKS1 — this module targets LUKS2 only, skipping" >&2
        fi
    done < <(sudo blkid -t TYPE=crypto_LUKS -o device 2>/dev/null)
}

# _tpm_has_token_type <device> <recovery|tpm2|password>
# True if ANY slot on the device has this type, regardless of slot number.
# This — not a slot index — is the mechanism systemd-cryptenroll itself uses
# for idempotency and for --wipe-slot=<type>, so it's what this module keys
# off of throughout.
_tpm_has_token_type() {
    local device_path="$1" token_type="$2" listing
    listing="$(sudo systemd-cryptenroll "${device_path}" 2>/dev/null)"
    echo "${listing}" | awk 'NR>1{print $2}' | grep -qx "${token_type}"
}

# _tpm_show_slots <device>
# Prints the current slot/type table for a device. Informational only —
# systemd-cryptenroll assigns new enrollments to the lowest free slot
# automatically and there is no way to pin placement, so this exists purely
# to make the actual, resulting layout visible after an enrollment.
_tpm_show_slots() {
    local device_path="$1"
    echo
    log_info "Current slot layout for ${device_path}:"
    sudo systemd-cryptenroll "${device_path}" 2>/dev/null | sed 's/^/    /'
    echo
}

# _tpm_device_uuid <device>
# The LUKS UUID — stable across reboots/reorders, unlike /dev/nvme0n1pN or
# /dev/sdXn paths. Used as the durable identifier in secret-storage titles so
# multiple devices on the same host don't collide or drift if disks/partitions
# get renumbered.
_tpm_device_uuid() {
    sudo cryptsetup luksUUID "$1" 2>/dev/null
}

# _tpm_device_label <device>
# Best-effort human identifier (mountpoint) for display/storage titles only —
# never used for matching or lookup, since both paths and mountpoints can
# change. Falls back to the bare device path if no mountpoint is found (e.g.
# the device is locked).
_tpm_device_label() {
    local device_path="$1" mapper_name mountpoint
    mapper_name="$(lsblk -no NAME "${device_path}" 2>/dev/null | tail -1)"
    mountpoint="$(lsblk -no MOUNTPOINT "/dev/mapper/${mapper_name}" 2>/dev/null | head -1)"
    if [[ -n "${mountpoint}" ]]; then
        echo "${mountpoint}"
    else
        echo "${device_path}"
    fi
}

# _tpm_enroll_device <device_path>
# Single-device TPM2 enrollment body — shared by enroll-luks-tpm2's device
# loop and rotate-luks-key's post-rotation offer, so both stay in sync.
_tpm_enroll_device() {
    local device_path="$1"

    _tpm_ensure_recovery_key "${device_path}" || {
        log_warn "skipping ${device_path} — recovery key not confirmed"
        return 1
    }

    # Only ever wipe the tpm2 slot type — recovery/password slots are
    # never touched, no matter what.
    local wipe_flag=()
    if _tpm_has_token_type "${device_path}" "tpm2"; then
        log_info "Existing TPM2 enrollment found for ${device_path} — replacing it"
        wipe_flag=(--wipe-slot=tpm2)
    fi

    if sudo systemd-cryptenroll \
            "${wipe_flag[@]}" \
            --tpm2-device=auto \
            --tpm2-pcrs="0+2+5+7" \
            "${device_path}"; then
        log_info "Successfully enrolled TPM2 for ${device_path}"
        _tpm_show_slots "${device_path}"
        return 0
    else
        log_error "Failed to enroll TPM2 for ${device_path}"
        return 1
    fi
}

# Ensures a recovery key exists on the device. Only ever creates one when
# missing — never wipes or regenerates an existing recovery key. No
# --wipe-slot is ever used here, so other existing slots are untouched.
_tpm_ensure_recovery_key() {
    local device_path="$1"

    if _tpm_has_token_type "${device_path}" "recovery"; then
        log_info "disk-encryption: recovery key already enrolled for ${device_path}"
        return 0
    fi

    log_warn "disk-encryption: no recovery key found for ${device_path} — creating one now"
    echo
    echo "  You'll be prompted for the disk's existing passphrase. A new recovery"
    echo "  key will then be generated and printed below — store it somewhere safe."
    echo

    # Capture via Python's stdlib pty module rather than script(1) — script
    # is part of the full util-linux package, which Fedora now splits out of
    # the default install (util-linux-core only). python3 is already a hard
    # dependency here, and pty/os are stdlib, so this needs nothing extra.
    # pty.fork() gives the child a real controlling terminal, so echo
    # suppression and password-prompt handling behave exactly as if run
    # directly — no bare-pipe weirdness like the previous approach had.
    #
    # The transcript path is only *named* here, not created — mktemp -u
    # reserves a unique name without creating the file. It's created by the
    # sudo'd python worker below (as root, with O_EXCL), so the file is
    # root-owned for its entire lifecycle and root never has to open a file
    # a different user created.
    local temp_dir transcript_file
    if [[ -d /dev/shm ]]; then
        temp_dir="/dev/shm"
    else
        temp_dir="${TMPDIR:-/tmp}"
    fi
    transcript_file="$(mktemp -u "${temp_dir}/tpm-recovery.XXXXXX")"

    # sudo wraps the python worker itself, not the inner command. Elevation
    # happens once, in the caller's own tty, reusing the sudo timestamp
    # sudo-test/blkid already established earlier in the flow. Once python3
    # is running as root, systemd-cryptenroll — run inside its pty child —
    # needs no sudo of its own, avoiding a second, separate-tty authentication
    # prompt (sudo's per-tty ticket caching treats pty.spawn()'s pty as a
    # distinct tty from the shell the command was originally run from).
    #
    # The worker lives at workers/disk-encryption-pty-capture.py, a sibling
    # of this file's own shell/ directory inside this module's fetched
    # snapshot (contracts/manifest-spec.md D16: register.list entries point
    # straight at <module>/current/<src>) — resolved via BASH_SOURCE rather
    # than a deploy: entry, since nothing else needs this file placed
    # anywhere else on disk.
    local _de_dir; _de_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local _pty_worker="${_de_dir}/../workers/disk-encryption-pty-capture.py"
    if [[ ! -f "${_pty_worker}" ]]; then
        log_error "disk-encryption: PTY-capture worker not found at ${_pty_worker}"
        return 1
    fi

    sudo python3 "${_pty_worker}" "${transcript_file}" \
        systemd-cryptenroll --recovery-key "${device_path}"
    local capture_rc=$?

    if [[ ${capture_rc} -ne 0 ]]; then
        log_error "disk-encryption: recovery key capture failed for ${device_path} (worker exit ${capture_rc})"
        sudo rm -f "${transcript_file}" 2>/dev/null
        return 1
    fi

    # Read and remove via sudo too — the file is root-owned. This reuses
    # the same warm sudo timestamp as everything else in this flow, so it
    # doesn't reintroduce an extra password prompt.
    local recovery_transcript
    recovery_transcript="$(sudo cat "${transcript_file}" 2>/dev/null | _tpm_clean_transcript)"
    sudo shred -u "${transcript_file}" 2>/dev/null || sudo rm -f "${transcript_file}" 2>/dev/null

    # Verify by re-checking device state rather than trusting an exit code
    # (bash $PIPESTATUS and zsh $pipestatus aren't the same mechanism, and
    # pty.spawn()'s return value is a raw wait-status, not a plain exit code).
    if ! _tpm_has_token_type "${device_path}" "recovery"; then
        log_error "disk-encryption: recovery key enrollment did not succeed for ${device_path}"
        unset recovery_transcript
        return 1
    fi

    _tpm_show_slots "${device_path}"
    _tpm_offer_secret_storage "${device_path}" "${recovery_transcript}"
    unset recovery_transcript
}

# Strips ANSI escape sequences and carriage returns from a script(1)
# typescript so a captured transcript reads cleanly when stored as a note.
_tpm_clean_transcript() {
    sed $'s/\x1b\[[0-9;]*[a-zA-Z]//g' | tr -d '\r'
}

_tpm_strip_ansi() {
    printf '%s' "$1" | sed -E 's/\x1b\[[0-9;]*[a-zA-Z]//g'
}

# Offers to store the just-generated recovery key transcript in whichever of
# Bitwarden/1Password is installed and unlocked. Declines silently if neither
# is available — the key was already shown above either way. Title uses the
# LUKS UUID and mountpoint rather than the bare /dev path, so multiple
# devices on the same host stay distinguishable and stable across reboots.
_tpm_offer_secret_storage() {
    local device_path="$1" transcript="$2"
    transcript="$(_tpm_strip_ansi "${transcript}")"
    local host label uuid title
    host="$(hostname -s 2>/dev/null || echo unknown)"
    label="$(_tpm_device_label "${device_path}")"
    uuid="$(_tpm_device_uuid "${device_path}")"
    title="LUKS Recovery Key — ${host} — ${label} — ${uuid:0:8}"
    local have_bw=false have_op=false answer

    command -v bw &>/dev/null && [[ "$(_tpm_bw_status)" == "unlocked" ]] && have_bw=true
    command -v op &>/dev/null && op whoami &>/dev/null 2>&1 && have_op=true

    if [[ "${have_bw}" != "true" && "${have_op}" != "true" ]]; then
        log_info "disk-encryption: Bitwarden/1Password not available or unlocked — recovery key was only shown above"
        return 0
    fi

    if [[ "${have_bw}" == "true" ]]; then
        _read_prompt "  Save this recovery key to Bitwarden as a secure note? [y/N]: " answer
        [[ "$(_str_lower "${answer}")" == "y" ]] && _tpm_bw_store_recovery "${title}" "${transcript}"
    fi
    if [[ "${have_op}" == "true" ]]; then
        _read_prompt "  Save this recovery key to 1Password as a secure note? [y/N]: " answer
        [[ "$(_str_lower "${answer}")" == "y" ]] && _tpm_op_store_recovery "${title}" "${transcript}"
    fi
}

_tpm_bw_status() {
    [[ -z "${BW_SESSION:-}" ]] && return 0
    bw status 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin).get("status",""))' 2>/dev/null
}

_tpm_bw_store_recovery() {
    local title="$1" body="$2" encoded tmp_json

    tmp_json="$(mktemp)" || {
        log_error "disk-encryption: failed to create temp file for Bitwarden item"
        return 1
    }

    bw get template item 2>/dev/null | python3 -c '
import json, sys
tpl = json.load(sys.stdin)
tpl["type"] = 2
tpl["name"] = sys.argv[1]
tpl["secureNote"] = {"type": 0}
tpl["notes"] = sys.argv[2]
print(json.dumps(tpl))
' "${title}" "${body}" > "${tmp_json}"

    if [[ ! -s "${tmp_json}" ]]; then
        log_error "disk-encryption: failed to build Bitwarden item"
        rm -f "${tmp_json}"
        return 1
    fi

    encoded="$(bw encode < "${tmp_json}")"
    rm -f "${tmp_json}"

    if [[ -z "${encoded}" ]]; then
        log_error "disk-encryption: bw encode returned empty output"
        return 1
    fi

    if bw create item "${encoded}" >/dev/null 2>&1; then
        log_info "disk-encryption: recovery key stored in Bitwarden as '${title}'"
    else
        log_error "disk-encryption: failed to create Bitwarden item '${title}'"
        return 1
    fi
}

_tpm_op_store_recovery() {
    local title="$1" body="$2"
    if op item create --category "Secure Note" --title "${title}" "notesPlain=${body}" >/dev/null 2>&1; then
        log_info "disk-encryption: recovery key stored in 1Password as '${title}'"
    else
        log_error "disk-encryption: failed to create 1Password item '${title}'"
        return 1
    fi
}
